export const LoactionTypes = {
	SET_LOCATION: 'SET_LOCATION',
	SET_LONGITUDE: 'SET_LONGITUDE',
	SET_LATITUDE: 'SET_LATITUDE',
	SET_CURRENT_DATE: 'SET_CURRENT_DATE',
	SET_TIMESTAMP: 'SET_TIMESTAMP',
	SET_CREW_INFO: 'SET_CREW_INFO'
}